title: Ad Elisium
author: Marc Goulding Tojar
email: gouldingmarc@gmail.com
description: To the Heavens
github_username: MarcGoulding
baseurl: /hub

# Build settings
markdown: redcarpet
theme: minima
